### PR TITLE
The Twins VR simulation includes the fight as well

### PR DESCRIPTION
**Pull request by gena138**

### CODE REVIEW

**Comment by gena138** [comment]
This makes it so it automatically starts the fight, from where you can win or lose

**Comment by gena138** [comment]
If you're in VR, some of the processTime() function are also decreased, because no matter how horny Steele is, it's unlikely they would spend, in one case, literal days in VR

**Comment by gena138** [comment]
Added taursuit, Dr. Po, and Miniboss VR as well, per Fen's request :3

**Comment by Gedan** [comment]
Merged.

**Pull request closed without merging**
