### PR TITLE
Pippa XPac

### PR DESCRIPTION
**Pull request by TheAscension**

### CODE REVIEW

**Comment by AlabasterChimes** [comment]
Do you plan to add variations to other sex scenes based on the dominance meter?
I have been trying to get your attention on the forums but you havent been on. Just wanted to ask.
Otherwise nice job on what you added and I hope it gets Greenlit.

**Comment by TheAscension** [comment]
Sorry about that, Chimes.  I don't look at the forum very often (and, apparently wrongfully, thought I'd get email alerts).  I'll reply to your post on the forum.

**Comment by TheAscension** [comment]
Going to close this for the time being to potentially make some more changes.

**Comment by Fenoxo** [comment]
Okey dokeeeee

**Pull request closed without merging**
