### PR TITLE
Bizzy expansion

### PR DESCRIPTION
**Pull request by Somebody-Else-Entirely**
All the stuff for the Bizzy Expansion

### CODE REVIEW

**Comment by Somebody-Else-Entirely** [comment]
Updated with a fix for the Mitzi/Sera branding text not being shown, and fixed a flag I missed in the cheat ('backinbizzness' to reset Bizzy).

**Comment by Somebody-Else-Entirely** [comment]
And fixed some typos.

**Comment by Somebody-Else-Entirely** [comment]
More typo fixes

**Comment by Fenoxo** [comment]
Think I got all the newer fixes ported into master code. Gonna close this for now! 🥉 
Tyvm!

**Pull request closed without merging**
