### PR TITLE
Dynamic Nykke name display 

### PR DESCRIPTION
**Pull request by TheRealDrunkZombie**
Dynamically display "your eldest kip" or "Nykke"  in frostwyrm.as, plus various other fixes

### CODE REVIEW

**Comment by Jacques00** [comment]
I have had this issue corrected due to a bug report on the forums so these changes are no longer necessary. Chiefly because the "your eldest kip/daughter" was not always stated the same way in every instance of Nikke from the original text. Sometimes it was just named "your eldest" or "your oldest kip", etc.

Aside from that, any specific typos should be fine to highlight.

**Comment by TheRealDrunkZombie** [comment]
I didn't change any instances of "your eldest", "your oldest kip",  etc... I only made instances of "Nykke" dynamic so that the name doesn't appear if you haven't had the intro yet.

**Comment by Jacques00** [comment]
I am aware of that. The corrections I had made for the aforementioned bug fix has already made all instances of "Nykke" dynamic (switching between the character's generic and specific name) and retains the wording that the original text had from before the expansion was implemented (save for swapping the word "daughter" with "kip").

**Comment by TheRealDrunkZombie** [comment]
Awesome! Ignore my ignorant comment then.

**Comment by Fenoxo** [comment]
Sounds like we're good to close this then!

**Pull request closed without merging**
