### PR TITLE
Synthsap bug

### PR DESCRIPTION
**Pull request by gena138**
This typo has probably been in the game for years at this point, but it should now be possible get Synth Sap in the game

### CODE REVIEW

**Comment by gena138** [comment]
When I made this PR, I didn't realize the "Vanae: History" codex entry was a separate entry. I'm sure there's a reason that's not in the game I don't know about, but after checking the small bit of content that this check unlocks, I see no reason why reading the "Vanae" codex entry shouldn't unlock it, or why the commented-out "Vanae: History" entry can't just be merged into the "Vanae" entry

**Comment by Fenoxo** [comment]
It was intended to come as part of further expansions on the Vanae and
their sister race were done, but JimT left the community, and those threads
are not planned to be developed any longer.

**Comment by gena138** [comment]
Right, I get that further expansions of vanae and their sister race aren't gonna happen. I just think that the content which is unlocked by this check (which is selling skysap to Kelly until Xenogen manufactures a better version) doesn't seem to be unimplementable currently. It's written and doesn't reference any information that the player can't already know in this current version of the game, and having Xenogen manufacture a new TF similar to Honeydew and Honeypot makes sense to me.
I'm not trying to be argumentative or anything, just explaining my thinking. Even if more doesn't get developed for the vanae, changing this line of code makes sense to me personally

**Comment by Fenoxo** [comment]
Yeah this seems like a fine change. I'll go ahead and make the change on my end (and move Synth Sap to the transformatives category since nobody should have it in their save file yet, and it belongs there)

**Pull request closed without merging**
